# Generated by Django 2.1.1 on 2019-05-09 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('index', models.IntegerField(primary_key=True, serialize=False)),
                ('rev_comp_id', models.TextField()),
                ('categories', models.CharField(max_length=100)),
                ('review_count', models.IntegerField()),
                ('rating', models.FloatField()),
                ('rev_company_name', models.CharField(max_length=100)),
            ],
        ),
    ]
